### ISSUE TITLE
[FEATURE]Display the parameters of the Cadence script

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-Extension#102]
The extension currently displays some parameters as [object], which needs to be corrected as [object Object],[object Object]: Array.

**Comment by Peppermint1020** [comment]
https://app.increment.fi/swap?in=A.1654653399040a61.FlowToken&out=

**Comment by zzggo** [comment]
![Image](https://github.com/user-attachments/assets/00af8be5-215d-4c3c-b6af-6e1b75b29c18)

**Comment by Peppermint1020** [comment]
Test on extension prod version 2.5.21.

Test on flowty and flovatar.
<img width="382" alt="Screen Shot 2024-11-19 at 6 33 07 pm" src="https://github.com/user-attachments/assets/4f879521-32b2-4b01-8962-fd2204a89faa">
<img width="389" alt="Screen Shot 2024-11-19 at 6 33 42 pm" src="https://github.com/user-attachments/assets/c71be2cc-0450-47b8-ae14-6732039c768a">
