### ISSUE TITLE
[TRADO BUG]Add liquidity functionality just breaks with an error in Trado Farm

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-Extension#129]
Add liquidity needs to work so users can farm
Retro step:
https://www.loom.com/share/cb51ed50f0ae4c788b43b864950c311c?sid=97bca50c-503d-4377-acdd-c1f69271eee6

**Comment by zzggo** [comment]
https://evm.flowscan.io/tx/0xc5611a4b45f9bfa90e6f2999e239a0261182e2d81de59e105d5ab9161d8591ed

**Comment by Peppermint1020** [comment]
This bug already fixed in extension prod version 2.5.16
