### ISSUE TITLE
[BUG] Can not buy nft from flowty

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-Extension#131]
Failed in extension 2.5.15
![Image](https://github.com/user-attachments/assets/758a980a-441c-48e6-8b37-a99a781f1560)

**Comment by lmcmz** [comment]
According to our dev @zzggo, extension doesn't get `authz` and `pre-authz` request after clicking buy button.

**Comment by Peppermint1020** [comment]
This bug seems already resolved in flowty side.
Now I can phrase nft from flowty successfully.
![Image](https://github.com/user-attachments/assets/1f2b1345-cc2a-4013-95a9-57d26b858291)
