### ISSUE TITLE
[FEATURE] Storage Alert (Storage Card)

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-Extension#145]
### Issue to be solved

Background:
https://github.com/Outblock/FRW/issues/61

#### Get Storage and Available Balance Info

Our script API returns `getAccountInfo` cadence, which allow wallet to get the storage info under an account.
```swift
access(all) struct Result {
  access(all) let address: Address
  access(all) let balance: UFix64
  access(all) let availableBalance: UFix64
  access(all) let storageUsed: UInt64
  access(all) let storageCapacity: UInt64
  access(all) let storageFlow: UFix64,
}
```
If `storageCapacity - storageUsed < 10000` then it's insufficient storage

#### Notification
Currently, we use firebase remote config to control the notification messages. It use `news` at the moment.
For insufficient storage alert, we gonna add a new condition flag `insufficientStorage`, which user reach storage limit. 

#### Onchain Interaction
Any onchain Interaction, wallet need do a async check whether the storage is sufficient or not.

If it's send Flow Token or move action ( move fee ), the balance will be affected we need take count of the sending or move fee balance.  ( availableBalance - sent amount ) < 0.001
Other onchain Interaction, we only do the availableBalance check.

#### Storage Usage Card
Storage info card need to be displayed only under FLOW token detail page.

Figma: 
https://www.figma.com/design/Qs5stGXY2US8Dj8UDjsdQ5/FLOW--Extention-Design-v2.0.0?node-id=19322-3404&t=XuGSo0DCk4j4z7BJ-1

**Comment by tombeckenham** [comment]
The design was used in another feature https://www.figma.com/design/Qs5stGXY2US8Dj8UDjsdQ5/FLOW--Extention-Design-v2.0.0?node-id=16584-262&node-type=frame&t=wfFzCZHzFpyc9oWL-0

**Comment by tombeckenham** [comment]
Additional requirements:

we need update the storage alert condition:

```
if storageCapacity - storageUsed < 10000 {
   // Show insufficient storage alert
  return
} 
```

> Let me list out all scenarios with storage warning in action button:
> 
> Move token
> Move NFT
> Send Token
> Send NFT
> Sign Transaction on browser
> Sign Transaction on WalletConnect
>

**Comment by tombeckenham** [comment]
I am splitting up this ticket into multiple tickets:
#145 - This ticket will be for the storage info card
#168 - Generic transaction error handling
#169 - Handle failed transactions due to storage and prompt
#170 - Low on storage warning
#171 - Insufficient storage after action

**Comment by Peppermint1020** [comment]
This popup page already added.
@KK-UIUX 
Please review the UI part.
![Image](https://github.com/user-attachments/assets/6aa084b4-4782-4e3a-a241-a045711fab26)

**Comment by tombeckenham** [comment]
@Peppermint1020 what is happening with this issue?

**Comment by Peppermint1020** [comment]
Hi Tom @tombeckenham ,
The ticket has been completed. It was previously under UI review, and it seems the UI designer didn't close it. I'll move it to Done now.
