### ISSUE TITLE
[BUG] When a COA is active, clicking on token link doesn't open the correct link

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW-Extension#152]
### Describe the Bug

In Flow Wallet extension, when a COA is active, clicking on a token link doesn't open the correct link

### Expected experience

Clicking on a token link opens the correct link, regardless of which account is active within the wallet.

### Steps To Reproduce

1. In Flow Wallet extension, switch to COA account
2. Select FLOW token
3. Click on the token link
4. Observe the correct link not open

### Environment

```markdown
- Extension
```
<img width="374" alt="Screen Shot 2024-11-08 at 6 47 27 AM" src="https://github.com/user-attachments/assets/6f31cc94-0020-4e48-ac15-69f792dd4581">

**Comment by Peppermint1020** [comment]
#duplicate
https://github.com/Outblock/FRW-Extension/issues/154

Also create individual tickets which mention same issue for iOS and Android.
