### ISSUE TITLE
[IMPROVEMENT] Hide arrow button if token lacks external link

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-Extension#154]
**Description:** 
Currently, the arrow button is visible even when a token lacks an external link, leading to potential user confusion. The arrow button should only be shown if the token includes an external link. If there is no external link, the arrow button should be hidden.

**Expected Behavior:**

If a token contains an external link, the arrow button should appear.
If a token does not have an external link, the arrow button should be hidden.

**Steps to Reproduce:**

(1) choose a token from homepage.
(2) click the arrow icon.
![Image](https://github.com/user-attachments/assets/eeea726e-bfdf-48e0-bf3d-3d617dd1ef60)

**Acceptance Criteria:**

 

- [x] Arrow button is only displayed when a token includes an external link.

 

- [x] Arrow button is hidden when no external link is associated with the token.

**Comment by zzggo** [comment]
![Image](https://github.com/user-attachments/assets/8a025ef6-104e-448a-bf35-e9413a74de41)

**Comment by Peppermint1020** [comment]
This issue already solved in extension 2.5.20.

- [x] Arrow button is only displayed when a token includes an external link.


- [x] Arrow button is hidden when no external link is associated with the token.

**Comment by Peppermint1020** [comment]
Discuss with Hao:

Most of token's website field is empty
If it's empty, we override to flowscan url
The exception is flow token on evm, since it's native token. It should hard coded as https://flow.com/

Wait Cao update those url on the token list.

**Comment by Peppermint1020** [comment]
This feature already improved in extension prod version 2.6.3
