### ISSUE TITLE
[FEATURE] Handle failed transactions due to storage

### ISSUE THREAD

**Issue by tombeckenham** [onflow/FRW-Extension#169]
### Issue to be solved

The extension should handle failed transactions due to storage.

This ticket was created from #145 to split up the work, and is an extension of issue #168 to handle the specific case of the user not having enough storage to perform the transaction they requested in the extension.

This should be handled in components that listen to transactions. In the extension, this will in the following scenarios:
* Move NFT
* Send NFT
* Move Tokens
* Send Tokens

### Suggest A Solution

When error 1103 ErrCodeStorageCapacityExceeded is detected, then the user should be prompted to buy more flow.

The alert that appears is in this figma:
https://www.figma.com/design/Qs5stGXY2US8Dj8UDjsdQ5/FLOW--Extention-Design-v2.0.0?node-id=19333-3334&node-type=frame&t=ssOFJ3jPiBuF0bgw-0

NOTE: This alert should also be accessed from the activity list for activities that have this error. but we need a design for that. Will leave until requested by product

**Comment by Peppermint1020** [comment]
#171
