### ISSUE TITLE
FEVM Banner side bar

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-Extension#17]

**Comment by Peppermint1020** [comment]
The FEVM banner side bar is add in flow wallet web extension version 2.1.0(debug).
But there are some  UI issues.

![Image](https://github.com/Outblock/FRW-Extension/assets/87978227/54b0d6f9-f272-4180-a66d-98842065eff4)

1. EVM banner should on the top of the side bar.
2. icon and text for main account.
3. position of the green dot.
