### ISSUE TITLE
[FEATURE] Low on storage warning

### ISSUE THREAD

**Issue by tombeckenham** [onflow/FRW-Extension#170]
### Issue to be solved

This ticket was created from #145  to split up the work.

The user should be warned when they are getting low on storage so they can buy more flow if they need to do storage related stuff.

This will save the user running into errors when they do storage operations

### Suggest A Solution

Display an alert on the following screens if the user is low on storage:
* Move NFT
* Send NFT
* Move Tokens
* Send Tokens

The user is low on storage if:
```
if storageCapacity - storageUsed < 10000 {
   // Show insufficient storage alert
  return
} 
```

The warning is designed in the following figma:
https://www.figma.com/design/Qs5stGXY2US8Dj8UDjsdQ5/FLOW--Extention-Design-v2.0.0?node-id=19332-3852&node-type=frame&t=ssOFJ3jPiBuF0bgw-0

**Comment by Peppermint1020** [comment]
#171
