### ISSUE TITLE
[FEATURE] Warn if storage will be insufficient after an action

### ISSUE THREAD

**Issue by tombeckenham** [onflow/FRW-Extension#171]
### Issue to be solved

If the user is about to perform an action that affects storage, they should be warned if that action will give them insufficient storage afterwards. That will help the user decide if they should perform the action or not, and prompt them to get more flow.

Note this was created from #145 to split up the work

### Suggest A Solution

In particular scenarios in the extension:
* Move NFT
* Send NFT
* Move Tokens
* Send Tokens

When the user is about to perform an action, check how many flow that action will use, then warn them. 

A design is here:
https://www.figma.com/design/Qs5stGXY2US8Dj8UDjsdQ5/FLOW--Extention-Design-v2.0.0?node-id=19332-6013&node-type=frame&t=ssOFJ3jPiBuF0bgw-0

**Comment by tombeckenham** [comment]
From @lmcmz:

```
// If it's other FT or NFT, the transferAmount is 0
// It's FLOW token, then it need to be the input value
var transferAmount = inputFlowTokenVaule ?? 0
let fixedMoveFee = 0.001
let averageTxFee = 0.001
let minimumStorageThreshold = 10000

let insufficientStorage = (storageCapacity - storageUsed) < minimumStorageThreshold

if insufficientStorage {
 // show alert
  return
}

if isMovingBetweenEVMAndFlow {
    transferAmount += fixedMoveFee
}

let noStorageAfterAction = availableBalance - transferAmount < averageTxFee

if noStorageAfterAction {
  // show alert (after this action)
  return
}
```

**Comment by Peppermint1020** [comment]
**Scenarios That May Trigger a Storage Alert:**

The following video shows the move and send from Flow Wallet to an EVM account, but the storage alert should also apply when moving/sending from EVM to Flow Wallet.

**Move Actions**

- Move FLOW from the homepage.
https://github.com/user-attachments/assets/d206fede-f215-4dd0-babb-2d100a2847ab

- Move other fungible tokens (FT) from the homepage.
https://github.com/user-attachments/assets/02e78494-8111-4661-bc10-45360e23f9d5

- Move NFTs from the homepage.
https://github.com/user-attachments/assets/c2286d66-c09f-4478-a213-66e547f18361

- Move FLOW from the FLOW token detail page.
https://github.com/user-attachments/assets/fa2745b0-3203-4a27-ad79-ba26f764d6ab

- Move other fungible tokens (FT) from the token detail page.
https://github.com/user-attachments/assets/6501d463-abe8-4b9c-8b58-9e3425995870

- Move NFTs from the NFT detail page.
https://github.com/user-attachments/assets/e61e3b3e-7b77-4fa4-a5a1-aaf68481549c



**Send Actions**
When test send action from flow address to flow address, recommend turn off free gas fee feature in Setting page.
https://github.com/user-attachments/assets/2c45ad46-2e9a-433b-8a11-746e242b96a9

User can use send action send to Flow account /EVM account/ EOA account(metamask)

- Send FLOW from the homepage.
https://github.com/user-attachments/assets/aab80c03-ee7c-423c-b37e-448c26a52fd4

- Send other fungible tokens (FT) from the homepage.
https://github.com/user-attachments/assets/d758298d-1387-48c3-8267-77f2c64ec8ff

- Send FLOW from the FLOW token detail page.
https://github.com/user-attachments/assets/d89f571f-f76f-4a8a-a8a9-ee2197314ca5

- Send other fungible tokens (FT) from the token detail page.
https://github.com/user-attachments/assets/c3bde7d6-1daa-4a4d-aed8-5d7cef123ae7

- Send NFTs from the NFT detail page.
https://github.com/user-attachments/assets/0bdd3a9e-00ad-42c3-bf6c-14fb20965889
 

These scenarios involve token transfers or operations that may reduce the account balance below the storage threshold, triggering a storage alert.
@jeden

**Comment by tombeckenham** [comment]
**Move operations**
- [x] Move FLOW from the homepage.
- [x] Move other fungible tokens (FT) from the homepage.
- [x] Move NFTs from the homepage.
- [x] Move FLOW from the FLOW token detail page.
- [x] Move other fungible tokens (FT) from the token detail page.
- [x] Move NFTs from the NFT detail page.


**Send Actions**

- [x] Send FLOW from the homepage.
- [x] Send other fungible tokens (FT) from the homepage.
- [x] Send FLOW from the FLOW token detail page.
- [x] Send other fungible tokens (FT) from the token detail page.
- [ ] Send NFTs from the NFT detail page.
