### ISSUE TITLE
FEVM Welcome Page

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-Extension#18]

**Comment by Peppermint1020** [comment]
FEVM welcome page is already add in flow wallet web extension 2.1.0.
But there some ui problems not match with UI design.


![Image](https://github.com/Outblock/FRW-Extension/assets/87978227/63bdf551-2ce7-4fc1-a10c-6f992d31ea90)

1. margin for skip button.
2. title text size.
3. enable button size.
4. no link linked with learn more button.
