### ISSUE TITLE
[BUG] Google backup failed in extension

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-Extension#194]
This issue reported by Hao.
He can't restore his account by google drive backup.
His scenario is there is a whitespace for the encrypted string.
<img width="832" alt="Screenshot_2024-11-21_at_1 52 50_pm" src="https://github.com/user-attachments/assets/8cd71535-31e6-4f9b-ac20-44d23e7c7cdc">
<img width="546" alt="Screenshot_2024-11-21_at_1 53 05_pm" src="https://github.com/user-attachments/assets/4c6ec12c-9065-47e6-a24c-04178d8f5a31">

**Comment by JeffreyDoyle** [comment]
@Peppermint1020 -- Can you please close this issue if we can confirm this fix has been published?

**Comment by Peppermint1020** [comment]
This issue is fixed, but not published yet, will publish in extension prod version 2.5.22
