### ISSUE TITLE
[BUG] Incorrect notification when moving FT other than FLOW token

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW-Extension#200]
### Describe the Bug

Moving FT other than FLOW token (eg: stFLOW) shows an incorrect notification, saying that FLOW token was moved between addresses. 
<img width="338" alt="Screen Shot 2024-11-21 at 8 34 14 AM" src="https://github.com/user-attachments/assets/7ff60e0b-b7a3-4572-aa03-25f07fa787fa">

### Expected experience

- The correct token name and amount must be displayed in the notification.
- When moving FLOW token, "FLOW" must be capitalized. 

### Steps To Reproduce

1. Move some FT other than FLOW between accounts
2. Observe incorrect notification, saying "Flow" was moved

### Environment

```markdown
- Mac
- Flow Wallet 2.5.20
```

**Comment by Peppermint1020** [comment]
Tested in Extension prod version 2.5.21 (internal test version)
There are two issues:
(1) When move from EVM to flow account, the token name is not displayed in notification. The receiver address is incorrect. 
<img width="347" alt="Screen Shot 2024-11-22 at 3 31 39 pm" src="https://github.com/user-attachments/assets/6d626f75-3f58-41be-9c34-04e2494b2e7a">
(2) The amount of token  display the input amount, not the actual transfer amount.
<img width="361" alt="Screen Shot 2024-11-22 at 3 24 22 pm" src="https://github.com/user-attachments/assets/dddf67d5-7271-4a4f-a25a-8fcdc482c3cd">

**Comment by Peppermint1020** [comment]
Tested in Extension prod version 2.5.21 (internal test version)
Issue 1 solved:
<img width="326" alt="Screen Shot 2024-11-22 at 3 56 38 pm" src="https://github.com/user-attachments/assets/8d25fb13-e3e5-4e7f-8a0a-902ae4ecdb43">
Issue 2 may implement later.
(3) Also, the "Click to view this transaction"  doesn't respond when clicked. Han said this is an issue with the link. The EVM TXID is not available at this time. Should we remove this text?  @lmcmz
