### ISSUE TITLE
[BUG] Chrome extension rejected due to Google Apis

### ISSUE THREAD

**Issue by tombeckenham** [onflow/FRW-Extension#210]
### Describe the Bug

The Firebase library injects a google analytics script. Script injections are dissalowed in Manifest V3. We had a fix in place to remove the code during builds, but it no longer works and we don't have anything in place that makes it easy to check if it's included.

### Expected experience

The extension should be uploadable to the app store and not include any script injections

### Steps To Reproduce

Upload the extension to the app store

### Environment

```markdown
- OS: Mac
- Node: 22
- pnpm: 9
```

**Comment by lmcmz** [comment]
resolved
