### ISSUE TITLE
Create EVM Address ( Existing User )

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-Extension#23]

**Comment by Peppermint1020** [comment]
The enable EVM feature already add in flow wallet web extension version 2.1.0(debug).
Users can create EVM address from EVM welcome page and view EVM address from side bar.
The demo video is attached below.

https://github.com/Outblock/FRW-Extension/assets/87978227/4b3ada16-2327-43bf-877c-0139064ed976

**Comment by Peppermint1020** [comment]
The enable EVM feature already add in flow wallet web extension version 2.1.0(debug).
Users can create EVM address from EVM welcome page and view EVM address from side bar.
The demo video is attached below.

https://github.com/Outblock/FRW-Extension/assets/87978227/4b3ada16-2327-43bf-877c-0139064ed976
