### ISSUE TITLE
[BUG] Incorrect storage warning when moving FLOW token

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW-Extension#247]
### Describe the Bug

Incorrect storage warnings "Insufficient storage after this action" are being displayed when moving FLOW between cadence accounts. 

These errors occur when the user has sufficient FLOW after the action to cover their storage usage.

In this example:  
![IMG_6809](https://github.com/user-attachments/assets/a17ed6be-d1b7-4eb6-889e-b23637e9da2b)
The user has >10 FLOW remaining after the transaction was submitted: (https://www.flowdiver.io/tx/611276caaf6729ec9f72ad9c24a8aa6851eaa6c6c1bb6866ee170503cbc36089) 

### Expected experience

Storage warnings must only be displayed when the action will reduce the users FLOW balance below what's required to cover their storage usage, or the minimum FLOW balance.

### Steps To Reproduce

1. Aquire some FLOW to an account
2. Use some amount of storage within the account
3. Transfer FLOW to another account, that is less than the FLOW required to cover the accounts storage usage
4. Observe the storage warning incorrectly displayed.

### Environment

```markdown
n/a
```

**Comment by tombeckenham** [comment]
@JeffreyDoyle which version of the extension was this?

**Comment by tombeckenham** [comment]
@JeffreyDoyle I believe this was fixed in 2.6.1 that was released last week. Could you please confirm?

**Comment by tombeckenham** [comment]
@Peppermint1020 could you please check this? I believe it was already fixed. I can't replicate

**Comment by Peppermint1020** [comment]
@tombeckenham Hi Tom, which version of the extension should I test with?

**Comment by Peppermint1020** [comment]
Tested on extension https://github.com/Outblock/FRW-Extension/actions/runs/12233319178
This issue is already solved in above build. No storage alert pop up when transfer flow token to other flow accounts
![Image](https://github.com/user-attachments/assets/35648ffd-36b7-4005-897d-f01f0e9fb606)
