### ISSUE TITLE
[FEATURE] Remove Metamask and rabby-wallet dependencies

### ISSUE THREAD

**Issue by tombeckenham** [onflow/FRW-Extension#295]
### Issue to be solved

Old depedencies are causing issues when upgrading others.

### Suggest A Solution

@zzggo says metamask is used in sign transaction, and rabby is for handling keyrings, we can make our own and remove those after upgrade

**Comment by Aryamai-ai** [comment]
“Hi @tombeckenham,
To address the dependency issue with MetaMask and Rabby-Wallet, I propose using a lightweight key management library, such as ethers.js or web3.js, which can handle signing transactions and managing keyrings without external dependency overhead. This approach will:
	1.	Remove reliance on outdated dependencies.
	2.	Ensure better control over upgrades and reduce breaking issues in the future
	example
const { Wallet } = require('ethers');  
const wallet = Wallet.createRandom();  
console.log('Address:', wallet.address);  
console.log('Private Key:', wallet.privateKey);  

This lightweight approach can replace the existing MetaMask/Rabby dependency seamlessly. Let me know if you’d like further implementation support!

**Comment by Peppermint1020** [comment]
Tested on https://github.com/Outblock/FRW-Extension/actions/runs/12371348090
Pass all tests.
(1) Restore accounts including google drive, seed phrase, key store, private key and device backup
(2) Sign messages
(3) switch account
(4) Sign typed data.
