### ISSUE TITLE
[BUG] UI issue --When send FT, transaction show double "-" 

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-Extension#37]
### Describe the Bug

There is an UI error in transaction list, need delete one of minus sign.
<img width="439" alt="Screen Shot 2024-03-19 at 11 59 16 am" src="https://github.com/Outblock/FRW-Extension/assets/87978227/b67d3a83-ce85-4b21-a741-ba3216a790ef">

### Expected experience

.

### Steps To Reproduce

1. Send some FT to another account.
2.  Check transaction list.

### Environment

```markdown
-Flow wallet web extension 2.1.1
```

**Comment by lmcmz** [comment]
Need update server API, the flow diver return different format in different network. 

Some of them with "-", some doesn't

**Comment by Peppermint1020** [comment]
This issue already solved in extension prod version 2.1.9
