### ISSUE TITLE
[BUG] This network selector should only be displayed if developer mode is turned on

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-Extension#62]
### Describe the Bug

This network selector in side bar should only be displayed if developer mode is turned on, right now it displays even if developer mode is turned off.

### Expected experience

If user turn off developer mode, hide network options in side bar.

### Steps To Reproduce

1. Go to setting page.
2. Go to  Developer mode.
3. turn off developer mode
4. open side bar.

### Environment

```markdown
-ios prod version 2.1.5(1)
-Android prod version r2.2.0
-extension prod 2.1.9
```

**Comment by Peppermint1020** [comment]
- [ v] extension

**Comment by zhouxl** [comment]
iOS done

**Comment by Peppermint1020** [comment]
Android done
