### ISSUE TITLE
[FEATURE]Extension Display of large token amounts

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-Extension#90]
On the homepage, large numbers like million, billion, and trillion need to be abbreviated, such as $2.45m, $1.456b. On the detail page, they should be displayed with commas, for example, 2,000,000,000.

**Comment by Peppermint1020** [comment]
Need a debug package, Multiply the quantity of each token by 10,000.

**Comment by Peppermint1020** [comment]
Tested on extension 2.5.20.
The token amount shows correctly in homepage token list.
![Image](https://github.com/user-attachments/assets/ed2d3fb1-ba3f-4b5b-be51-42b3fd354a5f)
But on the token detail page, the token name is displayed partially.
![Image](https://github.com/user-attachments/assets/a567c4a4-5c91-4f9e-b859-593a3e244770)
@zzggo

**Comment by zzggo** [comment]
![image](https://github.com/user-attachments/assets/c0fe8ab1-c9fa-43d6-9243-13d88c25bdf9)

**Comment by Peppermint1020** [comment]
Above bug already fixed in extension prod version 2.5.20.
![Image](https://github.com/user-attachments/assets/b237722b-6449-42b0-84c2-fb7dc34baaa9)
![Image](https://github.com/user-attachments/assets/8d78dca3-8e42-4cae-a88d-79d092d007f0)
