### ISSUE TITLE
[FEATURE] Dynamic address

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-Extension#96]

**Comment by Peppermint1020** [comment]
Tested on Extension version 2.5.20.

- [x]  Create account
- [x]  login account
- [x]  add token
- [x]  add nft collection
- [x] swap token
- [x] buy nft
- [x]  send flow/ft to other flow account
- [x]  send/move flow/ft to coa account
- [ ]  send flow/ft to EOA account
- [x] send nft to other flow account
- [x] send/move nft to coa account
- [x] send nft to EOA account
- [ ] COA send/move ft/flow to flow account
- [x] COA send ft/flow to other COA
- [x] COA send ft/flow to EOA account
- [x] COA send/move nft to flow account
- [x] COA send nft to other COA
- [x] COA send nft to EOA
- [x] mutiple accounts in sidebar
Issues find:
(1) When switch account, the child account of first profile will show in second profile sidebar, until reload side bar by click one of accounts.
(2) Token amount input box not shown when transfer ft from flow wallet to EOA/COA
(3) When I move ft from COA to flow account, I got following error message.https://www.flowscan.io/tx/d00ce6953f7cfdec3902edd7a3cda10f24464a62091b6dc629f9a86f2657a054

**Comment by Peppermint1020** [comment]
**Tested on Extension version 2.5.21.**

- [x] send flow/ft to EOA account
success tx id: https://www.flowscan.io/tx/df34c1dc06614079c91432b8ac789ec0836df7e13ec2e6615de5afd6bb35ad3e
- [x] COA send/move ft/flow to flow account
move success tx id:https://evm.flowscan.io/tx/0x7f1c2b495c3d339c846c97ecaade7fe30aad6ad1da8f4ee917248d1dc088bf83
send success tx id: https://evm.flowscan.io/tx/0xd22d9e989abbefdd0ff5a6f98a681279866901995db3dc8efb4d26c851148458

- [x] Issue 1

**Comment by Peppermint1020** [comment]
**Tested on Extension version 2.5.21.**
When i  import a account which have 2 addresses，only one main account address is shown in the wallet

**Comment by Peppermint1020** [comment]
Test session list:

- [ ] Create account
- [ ] Backup account by google drive
- [ ] login account by google drive/ private key / keystore /seed phrase
- [ ] add token in token list
- [ ] add nft collection
- [ ] swap token 
- [ ] buy nft from flowty/
- [ ] send flow/ft to other flow account
- [ ] send/move flow/ft to coa account
- [ ] send flow/ft to EOA account
- [ ] send nft to other flow account
- [ ] send/move nft to coa account
- [ ] send nft to EOA account
- [ ] COA send/move ft/flow to flow account
- [ ] COA send ft/flow to other COA
- [ ] COA send ft/flow to EOA account
- [ ] COA send/move nft to flow account
- [ ] COA send nft to other COA
- [ ] COA send nft to EOA
- [ ] Display multiple accounts in sidebar correctly
- [ ] When swapping between multiple accounts, show the corresponding EVM account

**Comment by caosbad** [comment]
- [x]  Create account
- [ ]  Backup account by google drive
- [ ]  login account by google drive/ private key / keystore /seed phrase
- [x]  add token in token list
- [x]  add nft collection
- [x]  swap token
- [ ]  buy nft from flowty/
- [x]  send flow/ft to other flow account
- [x]  send/move flow/ft to coa account
- [x]  send flow/ft to EOA account
- [x]  send nft to other flow account
- [ ]  send/move nft to coa account
- [x]  send nft to EOA account
- [x]  COA send/move ft/flow to flow account
- [x]  COA send ft/flow to other COA
- [x]  COA send ft/flow to EOA account
- [ ]  COA send/move nft to flow account
- [x]  COA send nft to other COA
- [x]  COA send nft to EOA
- [x]  Display multiple accounts in sidebar correctly
- [ ]  When swapping between multiple accounts, show the corresponding EVM account- [ ]

**Comment by Peppermint1020** [comment]
Fixed all issues in Test session thread, except following UI issue:
(1)The UI for the tick box is incorrect
![Image](https://github.com/user-attachments/assets/7184f1b9-529b-4d6d-81e1-aca064d98032)
(2) The bottom padding looks wrong.
![Image](https://github.com/user-attachments/assets/fa3003ac-6ed5-4331-baab-6a4a4acce7e8)

**Comment by Peppermint1020** [comment]
Fixed all issues in prod 2.5.22
